### ISSUE TITLE
do you think you could include TacoTron2 and make a pecs board?

### ISSUE THREAD

**Issue by BluePrintRandom** [cutiepi-io/cutiepi-firmware#1]
do you think you could include TacoTron2 and make a pecs board?

proloquo2go voice is all garbled 

this looks like it could be cheap + superior 
ps
potentially even integrating gesture recognition for sign language also would be good.

**Comment by penk** [comment]
Hi @BluePrintRandom , thanks for the suggestion. I think the goal of cutiepi-board (the carrier board) is to provide a base for others to build upon.
